###################################################################

# Created by write_sdc on Wed May 20 22:23:24 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
create_clock [get_ports clk]  -name sys_clk  -period 10  -waveform {0 5}
set_clock_uncertainty 0.5  [get_clocks sys_clk]
set_clock_transition -max -rise 0.15 [get_clocks sys_clk]
set_clock_transition -max -fall 0.15 [get_clocks sys_clk]
set_clock_transition -min -rise 0.15 [get_clocks sys_clk]
set_clock_transition -min -fall 0.15 [get_clocks sys_clk]
set_false_path   -from [get_ports irq_5]
set_false_path   -from [get_ports irq_6]
set_false_path   -from [get_ports irq_7]
set_false_path   -from [get_ports resetn]
set_false_path   -from [get_ports ser_rx]
set_false_path   -to [get_ports flash_csb]
set_false_path   -to [get_ports flash_clk]
set_input_delay -clock sys_clk  5  [get_ports ser_rx]
set_input_delay -clock sys_clk  5  [get_ports iomem_ready]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[31]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[30]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[29]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[28]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[27]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[26]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[25]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[24]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[23]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[22]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[21]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[20]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[19]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[18]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[17]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[16]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[15]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[14]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[13]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[12]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[11]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[10]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[9]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[8]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[7]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[6]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[5]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[4]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[3]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[2]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[1]}]
set_input_delay -clock sys_clk  5  [get_ports {iomem_rdata[0]}]
set_input_delay -clock sys_clk  5  [get_ports flash_io0_di]
set_input_delay -clock sys_clk  5  [get_ports flash_io1_di]
set_input_delay -clock sys_clk  5  [get_ports flash_io2_di]
set_input_delay -clock sys_clk  5  [get_ports flash_io3_di]
set_output_delay -clock sys_clk  5  [get_ports flash_csb]
set_output_delay -clock sys_clk  5  [get_ports flash_clk]
set_output_delay -clock sys_clk  5  [get_ports iomem_valid]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wstrb[3]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wstrb[2]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wstrb[1]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wstrb[0]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[31]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[30]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[29]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[28]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[27]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[26]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[25]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[24]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[23]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[22]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[21]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[20]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[19]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[18]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[17]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[16]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[15]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[14]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[13]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[12]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[11]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[10]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[9]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[8]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[7]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[6]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[5]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[4]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[3]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[2]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[1]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_addr[0]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[31]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[30]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[29]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[28]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[27]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[26]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[25]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[24]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[23]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[22]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[21]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[20]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[19]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[18]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[17]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[16]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[15]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[14]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[13]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[12]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[11]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[10]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[9]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[8]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[7]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[6]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[5]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[4]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[3]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[2]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[1]}]
set_output_delay -clock sys_clk  5  [get_ports {iomem_wdata[0]}]
set_output_delay -clock sys_clk  5  [get_ports ser_tx]
set_output_delay -clock sys_clk  5  [get_ports flash_io0_oe]
set_output_delay -clock sys_clk  5  [get_ports flash_io1_oe]
set_output_delay -clock sys_clk  5  [get_ports flash_io2_oe]
set_output_delay -clock sys_clk  5  [get_ports flash_io3_oe]
set_output_delay -clock sys_clk  5  [get_ports flash_io0_do]
set_output_delay -clock sys_clk  5  [get_ports flash_io1_do]
set_output_delay -clock sys_clk  5  [get_ports flash_io2_do]
set_output_delay -clock sys_clk  5  [get_ports flash_io3_do]
